# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /external/repos/git/jippi

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /external/repos/git/jippi

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /external/repos/git/jippi/CMakeFiles /external/repos/git/jippi/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /external/repos/git/jippi/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jippi

# Build rule for target.
jippi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jippi
.PHONY : jippi

# fast build rule for target.
jippi/fast:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/build
.PHONY : jippi/fast

#=============================================================================
# Target rules for targets named test-all

# Build rule for target.
test-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-all
.PHONY : test-all

# fast build rule for target.
test-all/fast:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/build
.PHONY : test-all/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/main.cpp.s
.PHONY : main.cpp.s

src/rest/client/restclient.o: src/rest/client/restclient.cpp.o
.PHONY : src/rest/client/restclient.o

# target to build an object file
src/rest/client/restclient.cpp.o:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/rest/client/restclient.cpp.o
.PHONY : src/rest/client/restclient.cpp.o

src/rest/client/restclient.i: src/rest/client/restclient.cpp.i
.PHONY : src/rest/client/restclient.i

# target to preprocess a source file
src/rest/client/restclient.cpp.i:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/rest/client/restclient.cpp.i
.PHONY : src/rest/client/restclient.cpp.i

src/rest/client/restclient.s: src/rest/client/restclient.cpp.s
.PHONY : src/rest/client/restclient.s

# target to generate assembly for a file
src/rest/client/restclient.cpp.s:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/rest/client/restclient.cpp.s
.PHONY : src/rest/client/restclient.cpp.s

src/utils/string/stringutils.o: src/utils/string/stringutils.cpp.o
.PHONY : src/utils/string/stringutils.o

# target to build an object file
src/utils/string/stringutils.cpp.o:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/utils/string/stringutils.cpp.o
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/src/utils/string/stringutils.cpp.o
.PHONY : src/utils/string/stringutils.cpp.o

src/utils/string/stringutils.i: src/utils/string/stringutils.cpp.i
.PHONY : src/utils/string/stringutils.i

# target to preprocess a source file
src/utils/string/stringutils.cpp.i:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/utils/string/stringutils.cpp.i
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/src/utils/string/stringutils.cpp.i
.PHONY : src/utils/string/stringutils.cpp.i

src/utils/string/stringutils.s: src/utils/string/stringutils.cpp.s
.PHONY : src/utils/string/stringutils.s

# target to generate assembly for a file
src/utils/string/stringutils.cpp.s:
	$(MAKE) -f CMakeFiles/jippi.dir/build.make CMakeFiles/jippi.dir/src/utils/string/stringutils.cpp.s
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/src/utils/string/stringutils.cpp.s
.PHONY : src/utils/string/stringutils.cpp.s

test/runtests.o: test/runtests.cpp.o
.PHONY : test/runtests.o

# target to build an object file
test/runtests.cpp.o:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/runtests.cpp.o
.PHONY : test/runtests.cpp.o

test/runtests.i: test/runtests.cpp.i
.PHONY : test/runtests.i

# target to preprocess a source file
test/runtests.cpp.i:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/runtests.cpp.i
.PHONY : test/runtests.cpp.i

test/runtests.s: test/runtests.cpp.s
.PHONY : test/runtests.s

# target to generate assembly for a file
test/runtests.cpp.s:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/runtests.cpp.s
.PHONY : test/runtests.cpp.s

test/utils/string/stringutilstest.o: test/utils/string/stringutilstest.cpp.o
.PHONY : test/utils/string/stringutilstest.o

# target to build an object file
test/utils/string/stringutilstest.cpp.o:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/utils/string/stringutilstest.cpp.o
.PHONY : test/utils/string/stringutilstest.cpp.o

test/utils/string/stringutilstest.i: test/utils/string/stringutilstest.cpp.i
.PHONY : test/utils/string/stringutilstest.i

# target to preprocess a source file
test/utils/string/stringutilstest.cpp.i:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/utils/string/stringutilstest.cpp.i
.PHONY : test/utils/string/stringutilstest.cpp.i

test/utils/string/stringutilstest.s: test/utils/string/stringutilstest.cpp.s
.PHONY : test/utils/string/stringutilstest.s

# target to generate assembly for a file
test/utils/string/stringutilstest.cpp.s:
	$(MAKE) -f CMakeFiles/test-all.dir/build.make CMakeFiles/test-all.dir/test/utils/string/stringutilstest.cpp.s
.PHONY : test/utils/string/stringutilstest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... jippi"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test-all"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/rest/client/restclient.o"
	@echo "... src/rest/client/restclient.i"
	@echo "... src/rest/client/restclient.s"
	@echo "... src/utils/string/stringutils.o"
	@echo "... src/utils/string/stringutils.i"
	@echo "... src/utils/string/stringutils.s"
	@echo "... test/runtests.o"
	@echo "... test/runtests.i"
	@echo "... test/runtests.s"
	@echo "... test/utils/string/stringutilstest.o"
	@echo "... test/utils/string/stringutilstest.i"
	@echo "... test/utils/string/stringutilstest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

